# Generated by Django 2.1.2 on 2018-11-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20181110_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[('Excellent', '1'), ('Good', '2'), ('Moderate', '3'), ('Poor', '4'), ('Very Poor', '5')]),
        ),
    ]
