# Generated by Django 2.1.2 on 2018-11-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20181111_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Excellent'), (2, 'Good'), (3, 'Moderate'), (4, 'Poor'), (5, 'Very Poor')]),
        ),
    ]
