# Generated by Django 2.1.2 on 2018-11-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20181111_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Moderate'), (2, 'Poor'), (1, 'Very Poor')]),
        ),
    ]
