# Generated by Django 2.1.2 on 2018-11-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='item_type',
            field=models.CharField(choices=[('BreakFast', 'BreakFast'), ('Meals', 'Meals'), ('Dinner', 'Dinner'), ('Special', 'Special'), ('All', 'All')], default='all', max_length=20),
        ),
    ]
