# Generated by Django 2.1.2 on 2018-11-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_type',
            field=models.CharField(choices=[('BreakFast', 'BreakFast'), ('Meals', 'Meals'), ('Dinner', 'Dinner'), ('Special', 'Special'), ('All', 'All')], default='All', max_length=20),
        ),
    ]
