# Generated by Django 2.1.2 on 2018-11-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20181110_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_type',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Main', 'Main'), ('Breads', 'Breads'), ('Italian', 'Italian'), ('Dessert', 'Desssert'), ('Specials', 'specials')], default='All', max_length=20),
        ),
    ]
