# Generated by Django 2.1.2 on 2018-10-30 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('contact', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('total_persons', models.CharField(max_length=4)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booktables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
