# Generated by Django 2.1.2 on 2018-10-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='total_persons',
            field=models.IntegerField(),
        ),
    ]
