# Generated by Django 2.1.2 on 2018-10-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0002_auto_20181030_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='date',
            field=models.DateField(verbose_name='%m/%d/%Y'),
        ),
    ]
