# Generated by Django 2.1.2 on 2018-11-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0005_auto_20181105_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
