# Generated by Django 2.1.2 on 2018-11-09 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Table', '0006_auto_20181106_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLawn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('total_persons', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklawns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
