# Generated by Django 2.1.2 on 2018-11-11 21:06

import Table.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0007_booklawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='contact',
            field=models.CharField(max_length=10, validators=[Table.models.validate_contact]),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='date',
            field=models.DateField(validators=[Table.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='time',
            field=models.TimeField(validators=[Table.models.validate_time]),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='total_persons',
            field=models.IntegerField(validators=[Table.models.validate_persons]),
        ),
    ]
