# Generated by Django 2.1.2 on 2018-11-11 21:17

import Table.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0008_auto_20181112_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklawn',
            name='contact',
            field=models.CharField(max_length=10, validators=[Table.models.validate_contact]),
        ),
        migrations.AlterField(
            model_name='booklawn',
            name='date',
            field=models.DateField(validators=[Table.models.validate_date]),
        ),
    ]
